[package]
name = "aptos-forge-pilot"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[features]
s3-tests = []
